### ISSUE TITLE
FS chat button doesn't show up when going full screen any longer

### ISSUE THREAD

**Issue by RYJASM** [FrankerFaceZ/Add-Ons#174]
FS chat button doesn't show up when going full screen any longer. FS chat overlay, but not UI activation button, will sometimes show if I set it to automatically show up when going full screen but it doesn't seem to always show up.

Google Chrome Console shows:

 FFZ [addons]: An error occured while enabling the add-on "fs-chat": TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at FSChat.onEnable (index.jsx:217:28)
    at module.js:337:17
    at async AddonManager._enableAddon (addons.js:450:27)
invoke @ logging.js:228

initialization
-------------------------------------------------------------------------------
[19:51:21] info | core: FrankerFaceZ v4.49.0 (s:twitch f:main b:3e9a1b65c5172c1953d2 c:7f109b4b48a5d5b1f2cf77d80b6912415be059de)
[19:51:21] info | core: Initial URL: https://www.twitch.tv/directory/following/channels
[19:51:21] info | site: Using: Twilight
[19:51:21] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[19:51:21] info | settings: Using Provider: LocalStorageProvider
[19:51:21] info | site.web_munch: require() grabbed in 1.80000ms.
[19:51:21] info | core: Loaded descriptions of 0 modules.
[19:51:21] info | settings: Initialization complete after 37.00000ms -- Values: 37 -- Profiles: 2
[19:51:21] info | site.fine: Installing MutationObserver.
[19:51:21] info | site: Loaded descriptions of 16 modules.
[19:51:21] info | site.elemental: Installing MutationObserver.
[19:51:21] info | experiments: Loaded information on 2 experiments.
[19:51:21] info | core: Initialization complete in 241.10000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "default"
i18n.format.time: "short"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "en"
data.use-staging: false
addons.dev.server: false
chat.bits.show: true
layout.display-bits-button: true
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 2
metadata.uptime.no-native: true
metadata.viewers: false
metadata.viewers.no-native: false
layout.swap-sidebars: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: null
chat.use-width: false
layout.use-chat-fix: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: 1
layout.side-nav.hide-offline: false
layout.hide-discover-luna: false
layout.prime-offers: true
layout.discover: true
channel.hide-unfollow: false
chat.hype.show-pinned: true
channel.round-avatars: true
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
layout.portrait-invert: false
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
theme.disable-auto-dark: false
theme.can-dark: true
theme.is-dark: true
theme.color.background: ""
theme.color.text: ""
theme.legacy-dark-input: false
theme.color.accent: ""
theme.color.tooltip.background: ""
theme.color.tooltip.text: ""
theme.color.chat-background: ""
theme.color.chat-text: ""
theme.color.chat-accent: ""
theme.font.size: 13
directory.show-channel-avatars: undefined
directory.hide-live: false
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: false
channel.auto-click-chat: false
player.gain.enable: false
player.gain.no-volume: false
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.fade-pause-buffer: false
player.ext-hide: 0
player.captions.font-size: ""
player.captions.font-family: ""
player.compressor.enable: true
player.compressor.shortcut: null
player.hide-event-bar: false
ffz.show-new-settings: true
directory.block-titles: []
__filter:directory.block-titles: null
addon.seventv_emotes.badges: true
addon.seventv_emotes.global_emotes: true
addon.seventv_emotes.nametag_paints: true
addon.seventv_emotes.animated_avatars: true
addon.seventv_emotes.emote_updates: true
addon.seventv_emotes.channel_emotes: true
addon.fs-chat.bg.blur: 10
addon.fs-chat.height: "500"
addon.fs-chat.width: null
addon.fs-chat.bg.color: "rgba(0, 0, 0, 0.64)"
addon.unread-mentions-counter.counter-location: "icon"
ffzenhancing.focus_input_area_after_emote_select: true
ffzenhancing.keep_delay_low: true
ffzenhancing.keep_delay_low_delay: 8.5
ffzenhancing.keep_delay_low_delay_low_latency: 5
ffzenhancing.keep_delay_low_rate: 1.05
ffzenhancing.fix_tooltips: true
ffzenhancing.doubleclick_username_paste_in_chat: false
ffzenhancing.move_users_in_chat_to_bottom: true
ffzenhancing.hide_rooms_header: true
ffzenhancing.auto_reload_on_error_2000: true
ffzenhancing.auto_reload_on_hanged_video: true
ffzenhancing.auto_reload_on_hanged_video_after: 4
ffzenhancing.auto_check_player_quality: true
ffzenhancing.auto_check_player_compressor: false
ffzenhancing.pin_mentions: false
ffzenhancing.reset_after_delay: true
ffzenhancing.reset_after_delay_delay: 30
ffzenhancing.animate_static_gif_emotes_on_mouse_hover: false
ffzenhancing.auto_click_claim_bonus_points: true
ffzenhancing.fix_emote_select: true
ffzenhancing.highlight_user_messages: true
ffzenhancing.visibility_hook_time: 5
ffzenhancing.fix_addon_load: true
ffzenhancing.fix_video_freeze_on_tab_change: true
ffzenhancing.always_show_open_thread_button: false
chat.filtering.display-deleted: false
channel.extra-links: true
player.no-autoplay: false
player.home.autoplay: true
player.disable-content-warnings: false
player.button.pip: true
player.button.reset: true
player.gain.min: 0
player.gain.max: 2
player.compressor.default: false
player.allow-catchup: true
player.theatre.auto-enter: false
addon.seventv_emotes.unlisted_emotes: true
metadata.clip-download: true
metadata.featured-follow: true
metadata.player-stats: false
player.volume-scroll: false
player.gain.scroll: false
player.single-click-pause: false
player.mute-click: false
addon.unread-mentions-counter.ping-types: ["mention"]
addon.unread-mentions-counter.browser-notifications.icon-photo: "channel"
layout.is-minimal: false
ffz.search.matches-only: true

experiments
-------------------------------------------------------------------------------
Unique ID: aPN2zxPA8r6rV8KkABysiamWUMgI2NrI

FFZ | API-Based Link Lookups: true (r:0.3)
Twitch | TWILIGHT_AD_DENSITY_WIDGET: no (r:0, t:channel_id, c:cyr)
Twitch | channel_points_reward_limits_v2: control (r:0, t:channel_id, c:cyr)
Twitch | copo_multi_option_predictions: control (r:0, t:channel_id, c:cyr)
Twitch | ht_celeb_experiment: Control (r:0, t:channel_id, c:cyr)
Twitch | hype_train_all_time_high: hype_train_all_time_high_off (r:0, t:channel_id, c:cyr)
Twitch | more_default_quick_actions: control (r:0, t:channel_id, c:cyr)
Twitch | new_vs_returning: control (r:0, t:channel_id, c:cyr)
Twitch | persistent_goals_2: control (r:0, t:channel_id, c:cyr)
Twitch | project_ape: control (r:0, t:channel_id, c:cyr)
Twitch | views_from_twitch_m2: control (r:0, t:channel_id, c:cyr)
Twitch | community_insights: control (r:0.01, t:channel_id, c:cyr)
Twitch | checkout_ux_phase_1: variant_e (r:0.1, t:user_id)
Twitch | consent_tool_headline: E (r:0.14, t:device_id)
Twitch | brand_lift_survey_experiment_1: variant_1 (r:0.33, t:user_id)
Twitch | during_ad_messaging_eligibility: iteration2 (r:0.33, t:device_id)
Twitch | toga-turtle-street: control (r:0.34, t:channel_id, c:cyr)
Twitch | Devsite_create_apps_form_recaptcha: variant1 (r:0.5, t:user_id)
Twitch | Twilight Player Core NPM Distribution (Public): variant-a (r:0.5, t:device_id)
Twitch | bits_simplified_purchase: treatment (r:0.5, t:user_id)
Twitch | bits_top_nav_explanation : control (r:0.5, t:user_id)
Twitch | chat_ad_alerts: control (r:0.5, t:channel_id, c:cyr)
Twitch | creator_follow_cue: activity-feed (r:0.5, t:user_id)
Twitch | giftcard_redemption_in_checkout: experiment (r:0.5, t:device_id)
Twitch | mobile_native_web_transcode_mode: cbr_v1 (r:0.5, t:device_id)
Twitch | pg_personalized_crown_menu: control (r:0.5, t:device_id)
Twitch | sda_post_fill_drop: treatment (r:0.5, t:device_id)
Twitch | subscriber_recap: control (r:0.5, t:channel_id, c:cyr)
Twitch | toad_experiment: control (r:0.6, t:channel_id, c:cyr)
Twitch | disco_bpli: control (r:0.75, t:user_id)
Twitch | chat_happening_now_2023: control (r:0.8, t:user_id)
Twitch | auto_mod_smart_detection: control (r:0.9, t:channel_id, c:cyr)
Twitch | cheering_web_ux_improvements: treatment (r:0.95, t:user_id)
Twitch | hype_chat_buy_your_own: treatment (r:0.95, t:user_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | percolite-shelf-reranking-logged-in: variant1b (r:0.98, t:user_id)
Twitch | disco_carousel_shelf: control (r:0.99, t:user_id)
Twitch | disco_sprig_logged_out: control (r:0.99, t:device_id)
Twitch | guest_star_left_nav_online_channel_augmentation: allowed (r:0.99, t:device_id)
Twitch | mse_in_workers: treatment (r:0.99, t:device_id)

addons
-------------------------------------------------------------------------------
Known
7tv-emotes | enabled | 7TV v1.3.2
aplatypuss-emotes | disabled | Aplatypuss Emotes v1.0.0
ffzap-core | enabled | FFZ:AP Core v3.3.11
brcm | disabled | brcm v1.0.0
chatterino-badges | disabled | Chatterino v1.0.0
clip-confirm | disabled | ClipConfirm v1.0.4
deck | disabled | Deck v2.2.1
emoteless | disabled | emote_less_chat v1.0.6
ffzap-bttv | enabled | FFZ:AP BTTV v3.3.15
ffzap-liriklive | enabled | FFZ:AP LirikLIVE v3.2.2
first-message-highlighter | disabled | first_msg_highlight v1.0.2
fs-chat | enabled | fs-chat v1.5.1
inline-tab-completion | disabled | Inline Tab v1.2.4
ModTools | disabled | Mod Tools v1.0.1
new-account-highlighter | disabled | New Account Highlighter v1.1.1
poll-shim | disabled | poll_shim v0.2.2
prattlenot | disabled | PrattleNot v0.8.1
pronouns | disabled | pronouns v1.1.1
repetition-detector | disabled | repetition_detector v1.1.0
smm2-links | disabled | SMM2 Links v1.0.0
smokemotes | disabled | smokeys_utils v1.1.7
unread-mentions-counter | enabled | UnreadMentionsCounter v1.1.1

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | staging
loaded   | enabled  | load_tracker
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | emote_card
loaded   | enabled  | main_menu
loaded   | enabled  | site.bits_button
loaded   | enabled  | metadata
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
unloaded | disabled | translation_ui
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffzap-liriklive
loaded   | enabled  | addon.7tv-emotes
loaded   | enabled  | addon.7tv-emotes.api.emotes
loaded   | enabled  | addon.7tv-emotes.api.cosmetics
loaded   | enabled  | addon.7tv-emotes.api
loaded   | enabled  | addon.7tv-emotes.avatars
loaded   | enabled  | addon.7tv-emotes.badges
loaded   | enabled  | addon.7tv-emotes.emotes
loaded   | enabled  | addon.7tv-emotes.eventapi
loaded   | enabled  | addon.7tv-emotes.nametag-paints
loaded   | enabled  | addon.ffzap-bttv
loaded   | enabled  | addon.ffzap-core
loaded   | disabled | addon.fs-chat
loaded   | enabled  | addon.unread-mentions-counter
loaded   | enabled  | addon.ffz-enhancing-addon

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.effects.enable: true
chat.effects.FlipX: true
chat.effects.FlipY: true
chat.effects.ShrinkX: true
chat.effects.GrowX: true
chat.emotes.animated: 1
chat.effects.Slide: true
chat.effects.Appear: true
chat.effects.Leave: true
chat.effects.Rotate: true
chat.effects.Rainbow: true
chat.effects.HyperRed: true
chat.effects.Shake: true
chat.effects.Photocopy: true
chat.effects.Jam: true
chat.effects.Bounce: true
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.clickable: 2
chat.badges.version: 2
chat.filtering.color-mentions: false
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false},"ctx":"inline"},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true},"ctx":"inline"},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true},"ctx":"inline"},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true},"ctx":"inline"}]
chat.actions.hover: [{"action":"pin","appearance":{"type":"icon","icon":"ffz-i-pin"},"options":{},"display":{"mod_icons":true},"ctx":"hover"},{"action":"reply","appearance":{"type":"dynamic"},"options":{},"display":{},"ctx":"hover"}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 2
chat.scroller.smooth-scroll: 0
chat.input.hide-identity: false
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.inline-preview.enabled: true
chat.emotes.2x: 0
chat.emotes.limit-size: true
chat.banners.last-events: false
chat.input.show-mod-view: true
chat.input.show-highlight: true
chat.input.show-shield: true
chat.lines.padding: true
chat.bits.show: true
chat.bits.show-pinned: false
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.filtering.bold-mentions: true
chat.hide-community-highlights: true
chat.lines.alternate: false
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.input.show-elevate-your-message: true
chat.disable-handling: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
theme.color.chat-background: ""
theme.color.background: ""
theme.color.chat-text: ""
theme.color.text: ""
chat.lines.borders: 0
chat.width: null
chat.effective-width: 340
chat.actions.size: 16
chat.actions.hover-size: 30
chat.timestamp-size: null
chat.font-size: 13
chat.lines.emote-alignment: 0
chat.font-family: ""
ffzap.liriklive.global_emoticons: true
ffzap.liriklive.sub_emoticons: true
ffzap.betterttv.global_emoticons: true
ffzap.betterttv.pro_badges: true
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/default_wet.mp3"
ffzap.core.highlight_sound_types: ["badge","mention","term","user"]
ffzap.core.enable_highlight_sound: true
ffzap.core.message_deletion: 0
ffzap.core.highlight_sound_volume: 50
ffzap.betterttv.arbitrary_emoticons: true
chat.update-when-loaded: true
chat.banners.charity: false
chat.subs.gift-banner: false
chat.banners.hype-train: false
chat.banners.prediction: true
chat.banners.polls: true
chat.banners.drops: true
chat.tab-complete.emotes-without-colon: false
chat.hype.display-input: true
chat.actions.room-above: false
chat.filtering.blocked-types: {}
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: []
__filter:block-terms: null
chat.filtering.highlight-basic-badges: []
__filter:highlight-badges: null
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: []
__filter:highlight-users: null
chat.filtering.highlight-basic-terms: []
__filter:highlight-terms: null
chat.emotes.enabled: 2
chat.fix-bad-emotes: true
chat.emoji.replace-joiner: 1
chat.filtering.mention-priority: 0
ffzap.betterttv.emote_modifiers: true
ffzap.core.remove_spaces: false
chat.filtering.display-deleted: false
chat.replies.style: 1
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.want-mid: false
chat.name-format: 0
chat.badges.hidden: {}
chat.badges.custom-mod: true
chat.badges.custom-vip: true
chat.filtering.hidden-tokens: {}
chat.actions.room: []
ffzap.betterttv.channel_emoticons: true
chat.bits.animated: true
theme.tooltips-dark: false
chat.timestamp-format: "h:mm"
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.points.show-button: true
chat.emote-menu.combine-tabs: false
chat.emote-menu.stay-loaded: false
chat.emote-menu.show-quick-nav: false
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: false
chat.emote-menu.reduced-padding: false
chat.emote-menu.show-search: true
chat.emote-menu.clear-search: false
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.emote-menu.effect-tab: true
chat.emote-menu.show-emoji: true
chat.subs.show: 3
chat.subs.compact: false
tooltip.emote-images.animated: true
tooltip.images: true
tooltip.emote-images: true
tooltip.emote-sources: true
chat.emote-menu.shortcut: false
chat.mru.enabled: true
chat.tab-complete.limit-results: true
chat.tab-complete.ffz-emotes: true
chat.tab-complete.emoji: true
chat.tab-complete.prioritize-favorites: false
chat.tab-complete.prioritize-prefix-matches: false
chat.filtering.process-own: false
chat.rich.all-links: false
tooltip.badge-images: true
chat.extra-timestamps: true
chat.points.allow-highlight: 2
chat.emote-menu.default-tab: "channel"
chat.points.auto-rewards: false
ffzap.betterttv.pro_emoticons: true
chat.click-emotes: true
chat.sub-emotes: true
chat.bits.stack: 0
chat.bits.cheer-notice: true
chat.rich.hide-tokens: false
tooltip.link-images: true
tooltip.link-nsfw-images: false
chat.filtering.display-mod-action: 1

**Comment by tballas** [comment]
Not only is the button not showing, the shortcut key doesn't work, so, there's no way to toggle FS chat

**Comment by RYJASM** [comment]
Yep I also have that same issue. This is really annoying. FS chat is the top feature I use besides emotes.
